In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
import sqlite3

In [2]:
def find_2nd(string, substring):
    return string.find(substring, string.find(substring) + 1)
def find_1st(string, substring):
    return string.find(substring, string.find(substring))   

response = requests.get("https://newzoo.com/insights/rankings/top-10-countries-by-game-revenues")
soup = BeautifulSoup(response.content, "lxml")

Data=[]
Ranking=[]

In [3]:
post_ranking=soup.find_all("div", class_="rank-number")
post_table=soup.find_all("td", class_="")

In [4]:
for element in post_table:
    element=str(element)
    limpio=str(element[find_1st(element, '>')+1:find_2nd(element, '<')])
    Data.append(limpio.strip())

for element in post_ranking:
    element=str(element)
    limpio=str(element[find_1st(element, '>')+1:find_2nd(element, '<')])
    Ranking.append(limpio.strip())

In [5]:
dataJson={}
index=1
for i in range(100):
    try:
        dataJson[i] = {
            'Ranking': Ranking[i],
            'Country': Data[index],
            'Region': Data[index+1],
            'Population': Data[index+2],
            'IntPop': Data[index+3],
            'Revenues': Data[index+4]
        }
        index+=6
        
    except Exception as e:
        print("error: " + str(e))

In [6]:
dataJson

{0: {'Ranking': '1.',
  'Country': 'China',
  'Region': 'Asia-Pacific',
  'Population': '1,439.3M',
  'IntPop': '907.5M',
  'Revenues': '$40,854M'},
 1: {'Ranking': '2.',
  'Country': 'United States',
  'Region': 'North America',
  'Population': '331.0M',
  'IntPop': '283.9M',
  'Revenues': '$36,921M'},
 2: {'Ranking': '3.',
  'Country': 'Japan',
  'Region': 'Asia-Pacific',
  'Population': '126.5M',
  'IntPop': '101.5M',
  'Revenues': '$18,683M'},
 3: {'Ranking': '4.',
  'Country': 'South Korea',
  'Region': 'Asia-Pacific',
  'Population': '51.3M',
  'IntPop': '48.2M',
  'Revenues': '$6,564M'},
 4: {'Ranking': '5.',
  'Country': 'Germany',
  'Region': 'Europe',
  'Population': '83.8M',
  'IntPop': '75.5M',
  'Revenues': '$5,965M'},
 5: {'Ranking': '6.',
  'Country': 'United Kingdom',
  'Region': 'Europe',
  'Population': '67.9M',
  'IntPop': '61.8M',
  'Revenues': '$5,511M'},
 6: {'Ranking': '7.',
  'Country': 'France',
  'Region': 'Europe',
  'Population': '65.3M',
  'IntPop': '58.2M',
  'Revenues': '$3,987M'},
 7: {'Ranking': '8.',
  'Country': 'Canada',
  'Region': 'North America',
  'Population': '37.7M',
  'IntPop': '33.7M',
  'Revenues': '$3,051M'},
 8: {'Ranking': '9.',
  'Country': 'Italy',
  'Region': 'Europe',
  'Population': '60.5M',
  'IntPop': '52.7M',
  'Revenues': '$2,661M'},
 9: {'Ranking': '10.',
  'Country': 'Spain',
  'Region': 'Europe',
  'Population': '46.8M',
  'IntPop': '40.8M',
  'Revenues': '$2,656M'},
 10: {'Ranking': '11.',
  'Country': 'Australia',
  'Region': 'Asia-Pacific',
  'Population': '25.5M',
  'IntPop': '23.0M',
  'Revenues': '$2,006M'},
 11: {'Ranking': '12.',
  'Country': 'India',
  'Region': 'Asia-Pacific',
  'Population': '1,380.0M',
  'IntPop': '649.4M',
  'Revenues': '$1,977M'},
 12: {'Ranking': '13.',
  'Country': 'Mexico',
  'Region': 'Latin America',
  'Population': '128.9M',
  'IntPop': '93.5M',
  'Revenues': '$1,901M'},
 13: {'Ranking': '14.',
  'Country': 'Russia',
  'Region': 'Europe',
  'Population': '145.9M',
  'IntPop': '119.7M',
  'Revenues': '$1,796M'},
 14: {'Ranking': '15.',
  'Country': 'Brazil',
  'Region': 'Latin America',
  'Population': '212.6M',
  'IntPop': '152.2M',
  'Revenues': '$1,754M'},
 15: {'Ranking': '16.',
  'Country': 'Indonesia',
  'Region': 'Asia-Pacific',
  'Population': '273.5M',
  'IntPop': '174.1M',
  'Revenues': '$1,550M'},
 16: {'Ranking': '17.',
  'Country': 'Taiwan',
  'Region': 'Asia-Pacific',
  'Population': '23.8M',
  'IntPop': '20.4M',
  'Revenues': '$1,432M'},
 17: {'Ranking': '18.',
  'Country': 'Thailand',
  'Region': 'Asia-Pacific',
  'Population': '69.8M',
  'IntPop': '44.0M',
  'Revenues': '$942M'},
 18: {'Ranking': '19.',
  'Country': 'Turkey',
  'Region': 'Middle East &amp; Africa',
  'Population': '84.3M',
  'IntPop': '58.4M',
  'Revenues': '$893M'},
 19: {'Ranking': '20.',
  'Country': 'Saudi Arabia',
  'Region': 'Middle East &amp; Africa',
  'Population': '34.8M',
  'IntPop': '28.8M',
  'Revenues': '$855M'},
 20: {'Ranking': '21.',
  'Country': 'Netherlands',
  'Region': 'Europe',
  'Population': '17.1M',
  'IntPop': '16.1M',
  'Revenues': '$786M'},
 21: {'Ranking': '22.',
  'Country': 'Malaysia',
  'Region': 'Asia-Pacific',
  'Population': '32.4M',
  'IntPop': '28.1M',
  'Revenues': '$786M'},
 22: {'Ranking': '23.',
  'Country': 'Philippines',
  'Region': 'Asia-Pacific',
  'Population': '109.6M',
  'IntPop': '73.1M',
  'Revenues': '$689M'},
 23: {'Ranking': '24.',
  'Country': 'Poland',
  'Region': 'Europe',
  'Population': '37.8M',
  'IntPop': '31.3M',
  'Revenues': '$687M'},
 24: {'Ranking': '25.',
  'Country': 'Vietnam',
  'Region': 'Asia-Pacific',
  'Population': '97.3M',
  'IntPop': '56.0M',
  'Revenues': '$620M'},
 25: {'Ranking': '26.',
  'Country': 'Switzerland',
  'Region': 'Europe',
  'Population': '8.7M',
  'IntPop': '8.1M',
  'Revenues': '$618M'},
 26: {'Ranking': '27.',
  'Country': 'Hong Kong',
  'Region': 'Asia-Pacific',
  'Population': '7.5M',
  'IntPop': '6.8M',
  'Revenues': '$613M'},
 27: {'Ranking': '28.',
  'Country': 'Sweden',
  'Region': 'Europe',
  'Population': '10.1M',
  'IntPop': '9.3M',
  'Revenues': '$546M'},
 28: {'Ranking': '29.',
  'Country': 'Argentina',
  'Region': 'Latin America',
  'Population': '45.2M',
  'IntPop': '36.1M',
  'Revenues': '$507M'},
 29: {'Ranking': '30.',
  'Country': 'Iran',
  'Region': 'Middle East &amp; Africa',
  'Population': '84.0M',
  'IntPop': '55.2M',
  'Revenues': '$475M'},
 30: {'Ranking': '31.',
  'Country': 'Austria',
  'Region': 'Europe',
  'Population': '9.0M',
  'IntPop': '8.0M',
  'Revenues': '$456M'},
 31: {'Ranking': '32.',
  'Country': 'Belgium',
  'Region': 'Europe',
  'Population': '11.6M',
  'IntPop': '10.7M',
  'Revenues': '$454M'},
 32: {'Ranking': '33.',
  'Country': 'Israel',
  'Region': 'Middle East &amp; Africa',
  'Population': '8.7M',
  'IntPop': '7.6M',
  'Revenues': '$438M'},
 33: {'Ranking': '34.',
  'Country': 'Colombia',
  'Region': 'Latin America',
  'Population': '50.9M',
  'IntPop': '34.4M',
  'Revenues': '$417M'},
 34: {'Ranking': '35.',
  'Country': 'Egypt',
  'Region': 'Middle East &amp; Africa',
  'Population': '102.3M',
  'IntPop': '53.6M',
  'Revenues': '$401M'},
 35: {'Ranking': '36.',
  'Country': 'Norway',
  'Region': 'Europe',
  'Population': '5.4M',
  'IntPop': '5.0M',
  'Revenues': '$383M'},
 36: {'Ranking': '37.',
  'Country': 'Portugal',
  'Region': 'Europe',
  'Population': '10.2M',
  'IntPop': '8.7M',
  'Revenues': '$367M'},
 37: {'Ranking': '38.',
  'Country': 'Singapore',
  'Region': 'Asia-Pacific',
  'Population': '5.9M',
  'IntPop': '5.2M',
  'Revenues': '$359M'},
 38: {'Ranking': '39.',
  'Country': 'Denmark',
  'Region': 'Europe',
  'Population': '5.8M',
  'IntPop': '5.3M',
  'Revenues': '$325M'},
 39: {'Ranking': '40.',
  'Country': 'United Arab Emirates',
  'Region': 'Middle East &amp; Africa',
  'Population': '9.9M',
  'IntPop': '9.1M',
  'Revenues': '$313M'},
 40: {'Ranking': '41.',
  'Country': 'Chile',
  'Region': 'Latin America',
  'Population': '19.1M',
  'IntPop': '14.9M',
  'Revenues': '$308M'},
 41: {'Ranking': '42.',
  'Country': 'Finland',
  'Region': 'Europe',
  'Population': '5.5M',
  'IntPop': '5.0M',
  'Revenues': '$291M'},
 42: {'Ranking': '43.',
  'Country': 'Ireland',
  'Region': 'Europe',
  'Population': '4.9M',
  'IntPop': '4.6M',
  'Revenues': '$262M'},
 43: {'Ranking': '44.',
  'Country': 'Ukraine',
  'Region': 'Europe',
  'Population': '43.7M',
  'IntPop': '27.6M',
  'Revenues': '$261M'},
 44: {'Ranking': '45.',
  'Country': 'Romania',
  'Region': 'Europe',
  'Population': '19.2M',
  'IntPop': '14.2M',
  'Revenues': '$255M'},
 45: {'Ranking': '46.',
  'Country': 'Kazakhstan',
  'Region': 'Asia-Pacific',
  'Population': '18.8M',
  'IntPop': '15.1M',
  'Revenues': '$253M'},
 46: {'Ranking': '47.',
  'Country': 'South Africa',
  'Region': 'Middle East &amp; Africa',
  'Population': '59.3M',
  'IntPop': '39.0M',
  'Revenues': '$245M'},
 47: {'Ranking': '48.',
  'Country': 'New Zealand',
  'Region': 'Asia-Pacific',
  'Population': '4.8M',
  'IntPop': '4.4M',
  'Revenues': '$214M'},
 48: {'Ranking': '49.',
  'Country': 'Czechia',
  'Region': 'Europe',
  'Population': '10.7M',
  'IntPop': '9.1M',
  'Revenues': '$212M'},
 49: {'Ranking': '50.',
  'Country': 'Pakistan',
  'Region': 'Asia-Pacific',
  'Population': '220.9M',
  'IntPop': '52.9M',
  'Revenues': '$199M'},
 50: {'Ranking': '51.',
  'Country': 'Peru',
  'Region': 'Latin America',
  'Population': '33.0M',
  'IntPop': '19.7M',
  'Revenues': '$198M'},
 51: {'Ranking': '52.',
  'Country': 'Morocco',
  'Region': 'Middle East &amp; Africa',
  'Population': '36.9M',
  'IntPop': '26.4M',
  'Revenues': '$177M'},
 52: {'Ranking': '53.',
  'Country': 'Bangladesh',
  'Region': 'Asia-Pacific',
  'Population': '164.7M',
  'IntPop': '44.6M',
  'Revenues': '$159M'},
 53: {'Ranking': '54.',
  'Country': 'Hungary',
  'Region': 'Europe',
  'Population': '9.7M',
  'IntPop': '8.0M',
  'Revenues': '$154M'},
 54: {'Ranking': '55.',
  'Country': 'Nigeria',
  'Region': 'Middle East &amp; Africa',
  'Population': '206.1M',
  'IntPop': '73.9M',
  'Revenues': '$151M'},
 55: {'Ranking': '56.',
  'Country': 'Algeria',
  'Region': 'Middle East &amp; Africa',
  'Population': '43.9M',
  'IntPop': '23.4M',
  'Revenues': '$141M'},
 56: {'Ranking': '57.',
  'Country': 'Myanmar',
  'Region': 'Asia-Pacific',
  'Population': '54.4M',
  'IntPop': '19.2M',
  'Revenues': '$139M'},
 57: {'Ranking': '58.',
  'Country': 'Greece',
  'Region': 'Europe',
  'Population': '10.4M',
  'IntPop': '8.7M',
  'Revenues': '$120M'},
 58: {'Ranking': '59.',
  'Country': 'Kuwait',
  'Region': 'Middle East &amp; Africa',
  'Population': '4.3M',
  'IntPop': '3.7M',
  'Revenues': '$112M'},
 59: {'Ranking': '60.',
  'Country': 'Lebanon',
  'Region': 'Middle East &amp; Africa',
  'Population': '6.8M',
  'IntPop': '5.8M',
  'Revenues': '$111M'},
 60: {'Ranking': '61.',
  'Country': 'Iraq',
  'Region': 'Middle East &amp; Africa',
  'Population': '40.2M',
  'IntPop': '12.3M',
  'Revenues': '$107M'},
 61: {'Ranking': '62.',
  'Country': 'Slovakia',
  'Region': 'Europe',
  'Population': '5.5M',
  'IntPop': '4.7M',
  'Revenues': '$106M'},
 62: {'Ranking': '63.',
  'Country': 'Belarus',
  'Region': 'Europe',
  'Population': '9.4M',
  'IntPop': '7.4M',
  'Revenues': '$96M'},
 63: {'Ranking': '64.',
  'Country': 'Qatar',
  'Region': 'Middle East &amp; Africa',
  'Population': '2.9M',
  'IntPop': '2.6M',
  'Revenues': '$96M'},
 64: {'Ranking': '65.',
  'Country': 'Serbia',
  'Region': 'Europe',
  'Population': '8.7M',
  'IntPop': '6.7M',
  'Revenues': '$95M'},
 65: {'Ranking': '66.',
  'Country': 'Uzbekistan',
  'Region': 'Asia-Pacific',
  'Population': '33.5M',
  'IntPop': '19.5M',
  'Revenues': '$89M'},
 66: {'Ranking': '67.',
  'Country': 'Azerbaijan',
  'Region': 'Middle East &amp; Africa',
  'Population': '10.1M',
  'IntPop': '8.7M',
  'Revenues': '$87M'},
 67: {'Ranking': '68.',
  'Country': 'Ecuador',
  'Region': 'Latin America',
  'Population': '17.6M',
  'IntPop': '11.7M',
  'Revenues': '$86M'},
 68: {'Ranking': '69.',
  'Country': 'Dominican Republic',
  'Region': 'Latin America',
  'Population': '10.8M',
  'IntPop': '7.8M',
  'Revenues': '$79M'},
 69: {'Ranking': '70.',
  'Country': 'Bulgaria',
  'Region': 'Europe',
  'Population': '6.9M',
  'IntPop': '5.1M',
  'Revenues': '$76M'},
 70: {'Ranking': '71.',
  'Country': 'Tunisia',
  'Region': 'Middle East &amp; Africa',
  'Population': '11.8M',
  'IntPop': '7.4M',
  'Revenues': '$74M'},
 71: {'Ranking': '72.',
  'Country': 'Puerto Rico',
  'Region': 'Latin America',
  'Population': '2.9M',
  'IntPop': '2.4M',
  'Revenues': '$72M'},
 72: {'Ranking': '73.',
  'Country': 'Sri Lanka',
  'Region': 'Asia-Pacific',
  'Population': '21.4M',
  'IntPop': '9.4M',
  'Revenues': '$71M'},
 73: {'Ranking': '74.',
  'Country': 'Croatia',
  'Region': 'Europe',
  'Population': '4.1M',
  'IntPop': '3.3M',
  'Revenues': '$71M'},
 74: {'Ranking': '75.',
  'Country': 'Jordan',
  'Region': 'Middle East &amp; Africa',
  'Population': '10.2M',
  'IntPop': '7.5M',
  'Revenues': '$70M'},
 75: {'Ranking': '76.',
  'Country': 'Oman',
  'Region': 'Middle East &amp; Africa',
  'Population': '5.1M',
  'IntPop': '4.1M',
  'Revenues': '$70M'},
 76: {'Ranking': '77.',
  'Country': 'Lithuania',
  'Region': 'Europe',
  'Population': '2.7M',
  'IntPop': '2.3M',
  'Revenues': '$60M'},
 77: {'Ranking': '78.',
  'Country': 'Uruguay',
  'Region': 'Latin America',
  'Population': '3.5M',
  'IntPop': '2.7M',
  'Revenues': '$59M'},
 78: {'Ranking': '79.',
  'Country': 'Cambodia',
  'Region': 'Asia-Pacific',
  'Population': '16.7M',
  'IntPop': '7.3M',
  'Revenues': '$53M'},
 79: {'Ranking': '80.',
  'Country': 'Slovenia',
  'Region': 'Europe',
  'Population': '2.1M',
  'IntPop': '1.8M',
  'Revenues': '$51M'},
 80: {'Ranking': '81.',
  'Country': 'Guatemala',
  'Region': 'Latin America',
  'Population': '17.9M',
  'IntPop': '8.5M',
  'Revenues': '$51M'},
 81: {'Ranking': '82.',
  'Country': 'Cuba',
  'Region': 'Latin America',
  'Population': '11.3M',
  'IntPop': '5.9M',
  'Revenues': '$46M'},
 82: {'Ranking': '83.',
  'Country': 'Costa Rica',
  'Region': 'Latin America',
  'Population': '5.1M',
  'IntPop': '3.6M',
  'Revenues': '$44M'},
 83: {'Ranking': '84.',
  'Country': 'Luxembourg',
  'Region': 'Europe',
  'Population': '0.6M',
  'IntPop': '0.6M',
  'Revenues': '$41M'},
 84: {'Ranking': '85.',
  'Country': 'Paraguay',
  'Region': 'Latin America',
  'Population': '7.1M',
  'IntPop': '4.4M',
  'Revenues': '$38M'},
 85: {'Ranking': '86.',
  'Country': 'Latvia',
  'Region': 'Europe',
  'Population': '1.9M',
  'IntPop': '1.6M',
  'Revenues': '$37M'},
 86: {'Ranking': '87.',
  'Country': 'Ghana',
  'Region': 'Middle East &amp; Africa',
  'Population': '31.1M',
  'IntPop': '14.6M',
  'Revenues': '$37M'},
 87: {'Ranking': '88.',
  'Country': 'Bahrain',
  'Region': 'Middle East &amp; Africa',
  'Population': '1.7M',
  'IntPop': '1.6M',
  'Revenues': '$37M'},
 88: {'Ranking': '89.',
  'Country': 'Panama',
  'Region': 'Latin America',
  'Population': '4.3M',
  'IntPop': '3.0M',
  'Revenues': '$36M'},
 89: {'Ranking': '90.',
  'Country': 'Macau',
  'Region': 'Asia-Pacific',
  'Population': '0.6M',
  'IntPop': '0.6M',
  'Revenues': '$36M'},
 90: {'Ranking': '91.',
  'Country': 'Bosnia and Herzegovina',
  'Region': 'Europe',
  'Population': '3.3M',
  'IntPop': '2.3M',
  'Revenues': '$32M'},
 91: {'Ranking': '92.',
  'Country': 'Kenya',
  'Region': 'Middle East &amp; Africa',
  'Population': '53.8M',
  'IntPop': '19.3M',
  'Revenues': '$30M'},
 92: {'Ranking': '93.',
  'Country': 'Georgia',
  'Region': 'Middle East &amp; Africa',
  'Population': '4.0M',
  'IntPop': '2.8M',
  'Revenues': '$30M'},
 93: {'Ranking': '94.',
  'Country': 'Ethiopia',
  'Region': 'Middle East &amp; Africa',
  'Population': '115.0M',
  'IntPop': '25.2M',
  'Revenues': '$30M'},
 94: {'Ranking': '95.',
  'Country': 'Bolivia',
  'Region': 'Latin America',
  'Population': '11.7M',
  'IntPop': '6.1M',
  'Revenues': '$29M'},
 95: {'Ranking': '96.',
  'Country': 'Estonia',
  'Region': 'Europe',
  'Population': '1.3M',
  'IntPop': '1.2M',
  'Revenues': '$27M'},
 96: {'Ranking': '97.',
  'Country': 'Moldova',
  'Region': 'Europe',
  'Population': '4.0M',
  'IntPop': '2.9M',
  'Revenues': '$27M'},
 97: {'Ranking': '98.',
  'Country': 'Albania',
  'Region': 'Europe',
  'Population': '2.9M',
  'IntPop': '2.1M',
  'Revenues': '$27M'},
 98: {'Ranking': '99.',
  'Country': 'Nepal',
  'Region': 'Asia-Pacific',
  'Population': '29.1M',
  'IntPop': '8.4M',
  'Revenues': '$25M'},
 99: {'Ranking': '100.',
  'Country': 'Armenia',
  'Region': 'Middle East &amp; Africa',
  'Population': '3.0M',
  'IntPop': '2.2M',
  'Revenues': '$24M'}}

In [7]:
dfData = pd.DataFrame(dataJson)

In [8]:
con=sqlite3.connect("videojuegos.db")
dfData.to_sql("videojuegos", con)

In [9]:
dfsqlite=pd.read_sql_query("SELECT * FROM  videojuegos",con)
dfsqlite

,index,0,1,2,3,4,5,6,7,8,...,90,91,92,93,94,95,96,97,98,99
0,Ranking,1.,2.,3.,4.,5.,6.,7.,8.,9.,...,91.,92.,93.,94.,95.,96.,97.,98.,99.,100.
1,Country,China,United States,Japan,South Korea,Germany,United Kingdom,France,Canada,Italy,...,Bosnia and Herzegovina,Kenya,Georgia,Ethiopia,Bolivia,Estonia,Moldova,Albania,Nepal,Armenia
2,Region,Asia-Pacific,North America,Asia-Pacific,Asia-Pacific,Europe,Europe,Europe,North America,Europe,...,Europe,Middle East &amp; Africa,Middle East &amp; Africa,Middle East &amp; Africa,Latin America,Europe,Europe,Europe,Asia-Pacific,Middle East &amp; Africa
3,Population,"1,439.3M",331.0M,126.5M,51.3M,83.8M,67.9M,65.3M,37.7M,60.5M,...,3.3M,53.8M,4.0M,115.0M,11.7M,1.3M,4.0M,2.9M,29.1M,3.0M
4,IntPop,907.5M,283.9M,101.5M,48.2M,75.5M,61.8M,58.2M,33.7M,52.7M,...,2.3M,19.3M,2.8M,25.2M,6.1M,1.2M,2.9M,2.1M,8.4M,2.2M
5,Revenues,"$40,854M","$36,921M","$18,683M","$6,564M","$5,965M","$5,511M","$3,987M","$3,051M","$2,661M",...,$32M,$30M,$30M,$30M,$29M,$27M,$27M,$27M,$25M,$24M